repos:
- repo: local
  hooks:
  - id: ruff-format
    name: ruff format
    entry: uvx ruff format
    language: system
    types: [python]
    require_serial: true
  - id: ruff-check
    name: ruff check
    entry: uvx ruff check --fix
    language: system
    types: [python]
    require_serial: true
  - id: ty-check
    name: ty check
    entry: uvx ty check
    language: system
    types: [python]
    pass_filenames: false
  - id: karva-test
    name: karva test
    entry: uvx --python 3.13 --with ".[plot,json,bgc,train]" karva test
    language: system
    types: [python]
    pass_filenames: false
  # - id: zenzic-check
  #   name: Zenzic Audit
  #   entry: uvx zenzic check all
  #   language: system
  #   pass_filenames: false
  #   files: \.(md|toml)$