r"""Version metadata generated automatically by hatch-vcs.

This module provides version identifiers and VCS commit metadata for the Kaptive package.
It should not be modified manually or tracked in version control.

Attributes:
    version (str): Full version string.
    __version__ (str): Alias for [`version`][kaptive._version.version].
    version_tuple (tuple[int | str, ...]): Parsed version components tuple.
    __version_tuple__ (tuple[int | str, ...]): Alias for [`version_tuple`][kaptive._version.version_tuple].
    commit_id (str | None): Git commit hash associated with the build, if available.
    __commit_id__ (str | None): Alias for [`commit_id`][kaptive._version.commit_id].
"""

from __future__ import annotations

# file generated by vcs-versioning
# don't change, don't track in version control



__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = '3.3.0b1.dev0+g3a61c3640.d20260728'
__version_tuple__ = version_tuple = (3, 3, 0, 'b1', 'dev0', 'g3a61c3640.d20260728')

__commit_id__ = commit_id = None
