r"""Biosynthetic Gene Cluster (BGC) architectural model serialization and representations.

This module defines data models for storing and persistence of machine learning
parameters used by BGC architectural classifiers and Hidden Markov Model (HMM) predictors.

Classes:
    ArchitecturalModel: Container and serialization engine for BGC HMM architectural parameters.
"""

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import numpy.typing as npt


@dataclass
class ArchitecturalModel:
    r"""Container and serialization engine for BGC HMM architectural parameters.

    Stores emission centroids and logarithmic state transition matrices used by
    [`ArchitecturalPredictor`][kaptive.bgc.predictor.ArchitecturalPredictor] to perform
    Viterbi decoding across contig ORF features. Model parameters are generated by
    [`ArchitecturalTrainer`][kaptive.bgc.trainer.ArchitecturalTrainer].

    Attributes:
        centroids (npt.NDArray[np.float32]): Matrix of shape `(num_locus_types, num_features)`
            containing feature centroids for distinct BGC locus types.
        bg_centroid (npt.NDArray[np.float32]): Vector of shape `(num_features,)` representing
            the background (non-BGC) feature centroid profile.
        transitions (npt.NDArray[np.float32]): Square matrix of shape `(num_states, num_states)`
            containing logarithmic state transition probabilities between architectural states.
    """

    centroids: npt.NDArray[np.float32]
    bg_centroid: npt.NDArray[np.float32]
    transitions: npt.NDArray[np.float32]

    def save(self, path: str | Path) -> None:
        r"""Save model centroids and transition parameters to a compressed `.npz` archive.

        Args:
            path (str | Path): Destination file path for saving compressed NPZ archive.

        Raises:
            OSError: If the destination directory does not exist or file cannot be written.
        """
        p = Path(path)
        np.savez_compressed(
            p,
            centroids=self.centroids,
            bg_centroid=self.bg_centroid,
            transitions=self.transitions,
        )

    @classmethod
    def load(cls, path: str | Path) -> "ArchitecturalModel":
        r"""Load model parameters from a compressed `.npz` archive.

        Args:
            path (str | Path): Path to existing `.npz` model file.

        Returns:
            ArchitecturalModel: Loaded model instance with contiguous `np.float32` arrays.

        Raises:
            FileNotFoundError: If the specified file path does not exist.
            KeyError: If required arrays (`centroids`, `bg_centroid`, `transitions`) are missing.
        """
        p = Path(path)
        weights = np.load(p)
        return cls(
            centroids=np.ascontiguousarray(weights["centroids"].astype(np.float32)),
            bg_centroid=np.ascontiguousarray(weights["bg_centroid"].astype(np.float32)),
            transitions=np.ascontiguousarray(weights["transitions"].astype(np.float32)),
        )
