from collections.abc import Iterable
from dataclasses import dataclass
from functools import cache
from typing import NamedTuple

import numpy as np
import numpy.typing as npt
from numba import njit, prange

from kaptive.core.collections import BatchedContainer
from kaptive.core.interval import Intervals
from kaptive.core.seq import Sequences

# Constants ------------------------------------------------------------------------------------------------------------
MINHASH_DTYPE = np.dtype([
    ('hash', np.uint64),
    ('seq_idx', np.uint32),
    ('pos1', np.uint32)
])

RANDSTROBE_DTYPE = np.dtype([
    ('hash', np.uint64),
    ('seq_idx', np.uint32),
    ('pos1', np.uint32),
    ('pos2', np.uint32)
])


# Classes --------------------------------------------------------------------------------------------------------------
class Seed(NamedTuple):
    query_index: int
    target_index: int
    score: int
    offset: int


@dataclass(frozen=True, slots=True)
class Seeds(BatchedContainer[Seed, 'Seeds']):
    """A high-performance SoA container for alignment seeds.

    This class stores information about potential alignment regions (seeds) between query and target
    sequences. It is typically generated by a `RandstrobeIndex` search. The data is stored in a
    Structure-of-Arrays (SoA) layout for efficient processing.

    Attributes:
        query_indices (npt.NDArray[np.uint32]): A 1D array of indices specifying which query sequence
            each seed belongs to.
        target_indices (npt.NDArray[np.uint32]): A 1D array of indices specifying which target sequence
            each seed corresponds to.
        scores (npt.NDArray[np.uint32]): A 1D array of scores for each seed, typically representing
            the absolute count of shared randstrobes (the intersection size) between the sequences.
        offsets (npt.NDArray[np.int32]): A 1D array of diagonal offsets. The offset is calculated as
            `(query_pos - target_pos)` and is used to center the banded alignment.
    """
    query_indices: npt.NDArray[np.uint32]
    target_indices: npt.NDArray[np.uint32]
    scores: npt.NDArray[np.uint32]
    offsets: npt.NDArray[np.int32]

    def __len__(self) -> int:
        """Returns the number of seeds in the batch."""
        return len(self.query_indices)

    def __getitem__(self, item) -> 'Seed | Seeds':
        if isinstance(item, (int, np.integer)):
            if item < 0:
                item += len(self)
            if item < 0 or item >= len(self):
                raise IndexError("Batch index out of range")
            return Seed(
                self.query_indices[item],
                self.target_indices[item],
                self.scores[item],
                self.offsets[item]
            )
            
        if isinstance(item, slice):
            indices = np.arange(len(self))[item]
        else:
            item_arr = np.asarray(item)
            indices = np.nonzero(item_arr)[0] if item_arr.dtype.kind == 'b' else item_arr
            
        return Seeds(
            self.query_indices[indices],
            self.target_indices[indices],
            self.scores[indices],
            self.offsets[indices]
        )
        
    @classmethod
    def concat(cls, batches: Iterable['Seeds']) -> 'Seeds':
        batches = list(batches)
        if not batches:
            return cls.empty()
        return cls(
            np.concatenate([b.query_indices for b in batches]),
            np.concatenate([b.target_indices for b in batches]),
            np.concatenate([b.scores for b in batches]),
            np.concatenate([b.offsets for b in batches])
        )

    @classmethod
    def empty(cls) -> 'Seeds':
        """Creates an empty Seeds collection.

        Returns:
            Seeds: A new collection with zero-length arrays.
        """
        return cls(np.empty(0, dtype=np.uint32),
                   np.empty(0, dtype=np.uint32),
                   np.empty(0, dtype=np.uint32),
                   np.empty(0, dtype=np.int32))

    def filter(self, mask: npt.NDArray[np.bool_]) -> 'Seeds':
        """Returns a new Seeds collection containing only records where the mask is True.

        Args:
            mask (npt.NDArray[np.bool_]): A 1D boolean array used to filter the seeds.

        Returns:
            Seeds: A new, filtered collection.
        """
        return Seeds(
            self.query_indices[mask],
            self.target_indices[mask],
            self.scores[mask],
            self.offsets[mask]
        )

    def to_intervals(self, query_lengths: npt.NDArray[np.int32]) -> 'Intervals':
        """Converts seeds into Intervals on the target sequences.
        
        Since offset = query_pos - target_pos, we approximate target_pos as -offset.
        The end position is target_start + query_length.
        """
        t_starts = -self.offsets
        q_lens = query_lengths[self.query_indices]
        t_ends = t_starts + q_lens
        
        return Intervals(
            starts=t_starts,
            ends=t_ends,
            strands=np.ones(len(self), dtype=np.int8),
            original_indices=np.arange(len(self), dtype=np.int32)
        )
        
    def cull_overlaps(
        self,
        query_lengths: npt.NDArray[np.int32],
        max_overlap_fraction: float = 0.1,
        priority_mask: npt.NDArray[np.bool_] | None = None
    ) -> 'Seeds':
        """Greedily culls seeds that overlap significantly on the target sequence."""
        n = len(self)
        if n == 0:
            return self

        # Sort order: priority_mask (True first), then scores (descending)
        if priority_mask is None:
            priority_mask = np.zeros(n, dtype=np.bool_)
            
        order = np.lexsort((-self.scores, ~priority_mask)).astype(np.int32)

        # We pass target_indices as the 'names' array to only cull overlaps on the same contig
        intervals = self.to_intervals(query_lengths)
        kept_mask = intervals.cull_overlaps(
            order=order,
            max_overlap_fraction=max_overlap_fraction,
            group_by=self.target_indices.astype(np.int32)
        )
        return self.filter(kept_mask)

    def top_hits(self, min_score: int = 1) -> 'Seeds':
        """Reduces the batch to only the highest-scoring seed for each query.

        Args:
            min_score (int, optional): The minimum score for a seed to be returned.
                Defaults to 1, which filters out queries with zero score.

        Returns:
            Seeds: A new collection containing at most one seed per query.
        """
        if len(self) == 0:
            return self

        # np.lexsort prioritizes the last array.
        # Primary key: query_indices (ascending). Secondary: scores (descending via ~)
        order = np.lexsort((~self.scores, self.query_indices))

        # Find the first occurrence of each query (which corresponds to its highest score)
        _, unique_idx = np.unique(self.query_indices[order], return_index=True)

        # Map back to the original array indices and sort to preserve the original query order
        best_idx = order[unique_idx]
        best_idx.sort()

        best_batch = Seeds(
            self.query_indices[best_idx],
            self.target_indices[best_idx],
            self.scores[best_idx],
            self.offsets[best_idx]
        )

        if min_score > 0:
            return best_batch.filter(best_batch.scores >= min_score)

        return best_batch

    def extract_sequences(self, queries: Sequences, targets: Sequences) -> tuple[Sequences, Sequences]:
        """Extracts parallel batches of query and target sequences mapped by this seed batch.

        Args:
            queries (Sequences): The source collection of query sequences.
            targets (Sequences): The source collection of target sequences.

        Returns:
            tuple[Sequences, Sequences]: Paired sequences ready for alignment.
        """
        return queries[self.query_indices], targets[self.target_indices] # type: ignore


@dataclass(frozen=True, slots=True, kw_only=True)
class BaseKmerIndex:
    """A base class for high-performance k-mer based sequence indices utilizing Array of Structs (AoS)."""
    records:     npt.NDArray
    n_seqs:      int = 0
    is_sorted:   bool = False
    k:           int = 10

    def __len__(self) -> int:
        return len(self.records)

    @classmethod
    def empty(cls) -> 'BaseKmerIndex':
        raise NotImplementedError

    @classmethod
    def build(cls, batch: Sequences, **kwargs) -> 'BaseKmerIndex':
        raise NotImplementedError

    def _build_queries(self, queries: Sequences) -> 'BaseKmerIndex':
        raise NotImplementedError

    def _prep_queries(self, queries: 'BaseKmerIndex | Sequences') -> 'BaseKmerIndex':
        if not self.is_sorted:
            raise ValueError("Target index must be sorted by hash for binary search. Build it with sort_by_hash=True.")

        if isinstance(queries, Sequences):
            queries = self._build_queries(queries)

        if queries.is_sorted:
            raise ValueError("Query index must NOT be sorted by hash. Build it with sort_by_hash=False.")

        return queries

    def top_hits(self, queries: 'BaseKmerIndex | Sequences', min_score: int = 1) -> Seeds:
        """Finds the single best-matching target sequence for each query sequence.

        This method iterates through each query sequence in the `queries` index, finds all shared
        hashes with this (the target) index, and tallies the counts for each target sequence.
        The target with the highest number of shared hashes is reported as the top hit. By default,
        only hits with a score greater than zero are returned.

        Args:
            queries (BaseKmerIndex | Sequences): An index of query sequences, or `Sequences` to be
                indexed on the fly.
            min_score (int, optional): The minimum score for a seed to be returned. Defaults to 1, which
                filters out queries with no matching hashes. Set to 0 to include all queries.

        Returns:
            Seeds: A collection of seeds. If `min_score > 0`, the collection may contain fewer records
                than the number of input queries.
        """

        if len(queries) == 0 or len(self) == 0:
            return Seeds.empty()

        queries = self._prep_queries(queries)
        q_offsets = _compute_query_offsets(queries.records, queries.n_seqs)

        seeds = Seeds(*_intersect_top_hit_kernel(
            queries.records, q_offsets, queries.n_seqs,
            self.records, self.n_seqs
        ))

        if min_score > 0:
            return seeds.filter(seeds.scores >= min_score)

        return seeds


@dataclass(frozen=True, slots=True, kw_only=True)
class FracMinHashIndex(BaseKmerIndex):
    """A specialized index for fast nucleotide sequence comparisons using FracMinHash.
    
    This index generates a sparse sketch of sequence-specific minimizers (k-mers).
    It is extremely fast for finding large nucleotide sequence homologies and containment.
    """
    scaled: int = 100
    canonical: bool = True
    bits_per_char: int = 2
    lut: npt.NDArray[np.uint8] | None = None

    @classmethod
    def empty(cls) -> 'FracMinHashIndex':
        return cls(
            records=np.empty(0, dtype=MINHASH_DTYPE),
            n_seqs=0, is_sorted=False, k=21, scaled=100, canonical=True, bits_per_char=2, lut=None
        )

    @classmethod
    def build(cls, batch: Sequences, k: int = 21, scaled: int = 100, 
              canonical: bool = True, seed: int = 42, sort_by_hash: bool = False,
              lut: npt.NDArray[np.uint8] | None = None, bits_per_char: int = 2, **kwargs) -> 'FracMinHashIndex':
        if len(batch) == 0:
            return cls.empty()
            
        n_seqs = len(batch)
        kernel_lut = lut if lut is not None else _dna_lut()
        
        # Pass 1: Count fracminhashes per sequence to allocate exact memory footprint
        counts = _count_fracminhash_kernel(
            batch.seqs, batch.offsets, batch.lengths, kernel_lut, k, scaled, canonical, bits_per_char
        )
        
        if (total_hashes := np.sum(counts)) == 0:
            return cls.empty()
            
        # Generate exact write offsets via cumulative sum
        out_offsets = np.empty(n_seqs, dtype=np.uint32)
        current_offset = 0
        for i in range(n_seqs):
            out_offsets[i] = current_offset
            current_offset += counts[i]
            
        out_records = np.empty(total_hashes, dtype=MINHASH_DTYPE)
        
        # Pass 2: Populate the fracminhashes in parallel
        _populate_fracminhash_kernel(
            batch.seqs, batch.offsets, batch.lengths, kernel_lut, k, scaled, canonical, bits_per_char,
            out_offsets, out_records
        )
        
        if sort_by_hash:
            out_records = _radix_sort_records(out_records)
            
        return cls(
            records=out_records,
            n_seqs=n_seqs, is_sorted=sort_by_hash, k=k, scaled=scaled, 
            canonical=canonical, bits_per_char=bits_per_char, lut=lut
        )
        
    def _build_queries(self, queries: Sequences) -> 'FracMinHashIndex':
        return self.build(queries, k=self.k, scaled=self.scaled, 
                          canonical=self.canonical, sort_by_hash=False,
                          lut=self.lut, bits_per_char=self.bits_per_char)
                          
    def to_sorted(self) -> 'FracMinHashIndex':
        if self.is_sorted:
            return self
        return self.__class__(
            records=_radix_sort_records(self.records),
            n_seqs=self.n_seqs, is_sorted=True, k=self.k, scaled=self.scaled, 
            canonical=self.canonical, bits_per_char=self.bits_per_char, lut=self.lut
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class RandstrobeIndex(BaseKmerIndex):
    """A specialized index for fast, homology-based amino-acid sequence comparisons using randstrobes.

    This class implements an index based on the randstrobe method, which generates sparse,
    sequence-specific minimizers. Randstrobes are robust to local insertions and deletions,
    making them highly effective for finding homologous sequences.

    The index stores hashes of randstrobes and their corresponding positions. The `search` and
    `top_hits` methods perform a fast lookup of shared randstrobes between a query index and this
    (the target) index to identify candidate alignment regions (seeds).

    The core logic for building the index and performing searches is implemented in highly optimized,
    parallelized Numba kernels.
    """
    s:           int = 5
    w_min:       int = 1
    w_max:       int = 5
    lut:         npt.NDArray[np.uint8] | None = None

    @classmethod
    def empty(cls) -> 'RandstrobeIndex':
        """Creates an empty RandstrobeIndex."""
        return cls(
            records=np.empty(0, dtype=RANDSTROBE_DTYPE),
            n_seqs=0, is_sorted=False, k=10, s=5, w_min=1, w_max=5, lut=None
        )

    @classmethod
    def build(cls, batch: Sequences, k: int = 10, s: int = 5, w_min: int = 1, w_max: int = 5,
              canonical: bool = True, seed: int = 42, sort_by_hash: bool = False,
              lut: npt.NDArray[np.uint8] | None = None, **kwargs) -> 'RandstrobeIndex':
        """Builds a RandstrobeIndex from a `Sequences` collection."""
        if s >= k:
            raise ValueError("Sub-k-mer size (s) must be strictly less than k-mer size (k).")

        if len(batch) == 0:
            return cls.empty()

        # Pass 1: Count randstrobes per sequence to allocate exact memory footprint
        kernel_lut = lut if lut is not None else _mmseqs12_lut()
        counts = _count_randstrobes_kernel(batch.seqs, batch.offsets, batch.lengths, kernel_lut, k, s, w_min)
        if (total_randstrobes := np.sum(counts)) == 0:
            return cls.empty()

        # Generate exact write offsets via cumulative sum
        out_offsets = np.empty(len(counts), dtype=np.uint32)
        current_offset = 0
        for i in range(len(counts)):
            out_offsets[i] = current_offset
            current_offset += counts[i]

        # Pre-allocate output arrays
        out_records = np.empty(total_randstrobes, dtype=RANDSTROBE_DTYPE)

        # Pass 2: Populate the randstrobes in parallel
        _populate_randstrobes_kernel(
            batch.seqs, batch.offsets, batch.lengths, kernel_lut, k, s, w_min, w_max, out_offsets,
            out_records
        )

        if sort_by_hash:
            out_records = _radix_sort_records(out_records)

        return cls(
            records=out_records,
            n_seqs=len(batch), is_sorted=sort_by_hash, k=k, s=s, w_min=w_min, w_max=w_max, lut=lut
        )

    def _build_queries(self, queries: Sequences) -> 'RandstrobeIndex':
        return self.build(queries, k=self.k, s=self.s, w_min=self.w_min, w_max=self.w_max, sort_by_hash=False, lut=self.lut)


# Functions ------------------------------------------------------------------------------------------------------------
@cache
def _mmseqs12_lut(fill_value: int = 12) -> npt.NDArray[np.uint8]:
    """Generates a 256-byte array for O(1) MMSEQS12 alphabet mapping."""
    mapping = {
        b'A': 0, b'S': 0, b'T': 0,
        b'L': 1, b'M': 1,
        b'I': 2, b'V': 2,
        b'K': 3, b'R': 3,
        b'E': 4, b'Q': 4,
        b'N': 5, b'D': 5,
        b'F': 6, b'Y': 6,
        b'C': 7,
        b'G': 8,
        b'H': 9,
        b'P': 10,
        b'W': 11
    }
    # Map unknowns (e.g. X) to 12
    lut = np.full(256, fill_value, dtype=np.uint8)
    for source_byte, target_int in mapping.items():
        lut[source_byte[0]] = target_int
        lut[source_byte.lower()[0]] = target_int
    lut.flags.writeable = False
    return lut

@cache
def _dna_lut(fill_value: int = 4) -> npt.NDArray[np.uint8]:
    """Generates a 256-byte array for O(1) DNA alphabet mapping."""
    lut = np.full(256, fill_value, dtype=np.uint8)
    mapping = {b'A': 0, b'C': 1, b'T': 2, b'G': 3}
    for source_byte, target_int in mapping.items():
        lut[source_byte[0]] = target_int
        lut[source_byte.lower()[0]] = target_int
    lut.flags.writeable = False
    return lut

@cache
def _aa_lut(fill_value: int = 22) -> npt.NDArray[np.uint8]:
    """Generates a 256-byte array for O(1) Amino Acid alphabet mapping."""
    lut = np.full(256, fill_value, dtype=np.uint8)
    # 20 standard AAs + U (Selenocysteine) + O (Pyrrolysine) = 22 valid chars
    # We map them to 0-21. B, Z, J, X, * map to fill_value for safety.
    mapping = {
        b'A': 0, b'C': 1, b'D': 2, b'E': 3, b'F': 4, b'G': 5, b'H': 6, b'I': 7, 
        b'K': 8, b'L': 9, b'M': 10, b'N': 11, b'P': 12, b'Q': 13, b'R': 14, 
        b'S': 15, b'T': 16, b'V': 17, b'W': 18, b'Y': 19, b'U': 20, b'O': 21
    }
    for source_byte, target_int in mapping.items():
        lut[source_byte[0]] = target_int
        lut[source_byte.lower()[0]] = target_int
    lut.flags.writeable = False
    return lut


# Kernels --------------------------------------------------------------------------------------------------------------
@njit(cache=True, nogil=True, inline='always')
def _splitmix64(x: np.uint64) -> np.uint64:
    """Fast, invertible 64-bit integer mixing function for randomizing hashes."""
    x = np.uint64(x + np.uint64(0x9E3779B97F4A7C15))
    x = (x ^ (x >> np.uint64(30))) * np.uint64(0xBF58476D1CE4E5B9)
    x = (x ^ (x >> np.uint64(27))) * np.uint64(0x94D049BB133111EB)
    return x ^ (x >> np.uint64(31))

@njit(cache=True, nogil=True)
def _radix_sort_records(records: npt.NDArray) -> npt.NDArray:
    """
    In-place radix sort of records by the 'hash' field. 
    By moving the entire struct simultaneously with the key, we ensure 
    perfect memory locality and eliminate scattered access payload permutations.
    """
    n = len(records)
    src = records.copy()
    dst = np.empty_like(records)
    
    hist = np.zeros(256, dtype=np.uint32)
    pos = np.zeros(256, dtype=np.uint32)
    
    for p in range(8):
        shift = np.uint64(p * 8)
        
        hist.fill(0)
        for i in range(n):
            byte_val = (src[i]['hash'] >> shift) & np.uint64(0xFF)
            hist[byte_val] += 1
            
        current_pos = np.uint32(0)
        for i in range(256):
            pos[i] = current_pos
            current_pos += hist[i]
            
        for i in range(n):
            byte_val = (src[i]['hash'] >> shift) & np.uint64(0xFF)
            write_idx = pos[byte_val]
            dst[write_idx] = src[i]
            pos[byte_val] += 1
            
        tmp = src
        src = dst
        dst = tmp
        
    return src

@njit(parallel=True, cache=True, nogil=True)
def _count_fracminhash_kernel(
        seqs: npt.NDArray[np.uint8], offsets: npt.NDArray[np.int32], lengths: npt.NDArray[np.int32],
        lut: npt.NDArray[np.uint8], k: int, scaled: int, canonical: bool, bits_per_char: int
) -> npt.NDArray[np.uint32]:
    n_seqs = len(offsets)
    counts = np.zeros(n_seqs, dtype=np.uint32)
    mask = (np.uint64(1) << np.uint64(bits_per_char * k)) - np.uint64(1)
    max_val = np.uint64(1) << np.uint64(bits_per_char)
    threshold = ~np.uint64(0) // np.uint64(scaled)

    for idx in prange(n_seqs): # type: ignore
        seq_len = lengths[idx]
        if seq_len < k:
            continue

        seq_start = offsets[idx]
        k_val_fwd = np.uint64(0)
        k_val_rev = np.uint64(0)
        valid_len = 0
        n_hashes = 0

        for j in range(seq_len):
            char = seqs[seq_start + j]
            val = np.uint64(lut[char])
            
            if val < max_val:
                k_val_fwd = ((k_val_fwd << np.uint64(bits_per_char)) & mask) | val
                valid_len += 1
                
                if canonical:
                    comp = val ^ np.uint64(2)
                    k_val_rev = (k_val_rev >> np.uint64(bits_per_char)) | (comp << np.uint64(bits_per_char * (k - 1)))
                
                if valid_len >= k:
                    if canonical:
                        h_val = min(k_val_fwd, k_val_rev)
                    else:
                        h_val = k_val_fwd
                        
                    h = _splitmix64(h_val)
                    if h <= threshold:
                        n_hashes += 1
            else:
                valid_len = 0
                k_val_fwd = np.uint64(0)
                k_val_rev = np.uint64(0)
                
        counts[idx] = n_hashes
    return counts

@njit(parallel=True, cache=True, nogil=True)
def _populate_fracminhash_kernel(
        seqs: npt.NDArray[np.uint8], offsets: npt.NDArray[np.int32], lengths: npt.NDArray[np.int32],
        lut: npt.NDArray[np.uint8], k: int, scaled: int, canonical: bool, bits_per_char: int,
        out_offsets: npt.NDArray[np.uint32], out_records: npt.NDArray
):
    n_seqs = len(offsets)
    mask = (np.uint64(1) << np.uint64(bits_per_char * k)) - np.uint64(1)
    max_val = np.uint64(1) << np.uint64(bits_per_char)
    threshold = ~np.uint64(0) // np.uint64(scaled)

    for idx in prange(n_seqs): # type: ignore
        seq_len = lengths[idx]
        if seq_len < k:
            continue

        seq_start = offsets[idx]
        out_s = out_offsets[idx]
        
        k_val_fwd = np.uint64(0)
        k_val_rev = np.uint64(0)
        valid_len = 0
        written = 0

        for j in range(seq_len):
            char = seqs[seq_start + j]
            val = np.uint64(lut[char])
            
            if val < max_val:
                k_val_fwd = ((k_val_fwd << np.uint64(bits_per_char)) & mask) | val
                valid_len += 1
                
                if canonical:
                    comp = val ^ np.uint64(2)
                    k_val_rev = (k_val_rev >> np.uint64(bits_per_char)) | (comp << np.uint64(bits_per_char * (k - 1)))
                
                if valid_len >= k:
                    pos = j - k + 1
                    if canonical:
                        h_val = min(k_val_fwd, k_val_rev)
                    else:
                        h_val = k_val_fwd
                        
                    h = _splitmix64(h_val)
                    if h <= threshold:
                        out_records[out_s + written]['hash'] = h
                        out_records[out_s + written]['seq_idx'] = idx
                        out_records[out_s + written]['pos1'] = pos
                        written += 1
            else:
                valid_len = 0
                k_val_fwd = np.uint64(0)
                k_val_rev = np.uint64(0)

@njit(parallel=True, cache=True, nogil=True)
def _pack_kernel(
    read_offsets: npt.NDArray[np.uint32], write_offsets: npt.NDArray[np.uint32], counts: npt.NDArray[np.uint32],
    in_records: npt.NDArray, out_records: npt.NDArray
):
    for idx in prange(len(counts)): # type: ignore
        c = counts[idx]
        if c > 0:
            r = read_offsets[idx]
            w = write_offsets[idx]
            out_records[w : w + c] = in_records[r : r + c]

@njit(parallel=True, cache=True, nogil=True)
def _count_randstrobes_kernel(
        seqs: npt.NDArray[np.uint8], offsets: npt.NDArray[np.int32], lengths: npt.NDArray[np.int32],
        lut: npt.NDArray[np.uint8], k: int, s: int, w_min: int
) -> npt.NDArray[np.uint32]:
    n_seqs = len(offsets)
    counts = np.zeros(n_seqs, dtype=np.uint32)

    for idx in prange(n_seqs): # type: ignore
        seq_len = lengths[idx]
        if seq_len < k:
            continue

        seq_start = offsets[idx]
        n_syncmers = 0

        # Scan for random open syncmers
        for i in range(seq_len - k + 1):
            min_s_hash = ~np.uint64(0)
            min_s_idx = -1

            # Check all s-mers within this k-mer window
            for j in range(k - s + 1):
                s_val = np.uint64(0)
                for c in range(s):
                    char = seqs[seq_start + i + j + c]
                    s_val = s_val * np.uint64(12) + np.uint64(lut[char])

                h = _splitmix64(s_val)
                if h < min_s_hash:
                    min_s_hash = h
                    min_s_idx = j

            # Open Syncmer condition: minimum s-mer is at the first or last position
            if min_s_idx == 0 or min_s_idx == (k - s):
                n_syncmers += 1

        # A sequence yields exactly (n_syncmers - w_min) randstrobes (if positive)
        if n_syncmers > w_min:
            counts[idx] = n_syncmers - w_min

    return counts


@njit(parallel=True, cache=True, nogil=True)
def _populate_randstrobes_kernel(
        seqs: npt.NDArray[np.uint8], offsets: npt.NDArray[np.int32], lengths: npt.NDArray[np.int32],
        lut: npt.NDArray[np.uint8], k: int, s: int, w_min: int, w_max: int, out_offsets: npt.NDArray[np.uint32],
        out_records: npt.NDArray
):
    n_seqs = len(offsets)

    for idx in prange(n_seqs): # type: ignore
        seq_len = lengths[idx]
        if seq_len < k:
            continue

        seq_start = offsets[idx]
        max_syncmers = seq_len - k + 1

        # Thread-local allocations to store localized syncmer data safely within prange
        syncmer_pos = np.empty(max_syncmers, dtype=np.uint32)
        syncmer_hash = np.empty(max_syncmers, dtype=np.uint64)
        n_syncmers = 0

        # 1. Identify and cache the syncmers
        for i in range(seq_len - k + 1):
            min_s_hash = ~np.uint64(0)
            min_s_idx = -1

            for j in range(k - s + 1):
                s_val = np.uint64(0)
                for c in range(s):
                    char = seqs[seq_start + i + j + c]
                    s_val = s_val * np.uint64(12) + np.uint64(lut[char])

                h = _splitmix64(s_val)
                if h < min_s_hash:
                    min_s_hash = h
                    min_s_idx = j

            if min_s_idx == 0 or min_s_idx == (k - s):
                syncmer_pos[n_syncmers] = i

                # Hash the full k-mer window to use for randstrobe linkage
                k_val = np.uint64(0)
                for c in range(k):
                    char = seqs[seq_start + i + c]
                    k_val = k_val * np.uint64(12) + np.uint64(lut[char])

                syncmer_hash[n_syncmers] = _splitmix64(k_val)
                n_syncmers += 1

        # 2. Build Order-2 Randstrobes from the cached syncmers
        out_idx = out_offsets[idx]

        for i in range(n_syncmers - w_min):
            h1 = syncmer_hash[i]
            min_randstrobe_hash = ~np.uint64(0)
            best_j = -1

            end_j = i + w_max + 1
            if end_j > n_syncmers:
                end_j = n_syncmers

            for j in range(i + w_min, end_j):
                h2 = syncmer_hash[j]

                # Combine hashes asymmetrically (XOR of hashed values)
                combined = _splitmix64(h1 ^ _splitmix64(h2))
                if combined < min_randstrobe_hash:
                    min_randstrobe_hash = combined
                    best_j = j

            if best_j != -1:
                out_records[out_idx]['hash'] = min_randstrobe_hash
                out_records[out_idx]['seq_idx'] = idx
                out_records[out_idx]['pos1'] = syncmer_pos[i]
                out_records[out_idx]['pos2'] = syncmer_pos[best_j]
                out_idx += 1


@njit(cache=True, nogil=True)
def _compute_query_offsets(q_records: npt.NDArray, num_queries: int) -> npt.NDArray[np.uint32]:
    """Finds the boundary indices for each query sequence in the flat hash array."""
    q_offsets = np.zeros(num_queries + 1, dtype=np.uint32)
    if len(q_records) == 0:
        return q_offsets

    current_query = 0
    for i in range(len(q_records)):
        q = q_records[i]['seq_idx']
        while current_query < q:
            current_query += 1
            q_offsets[current_query] = i
            
    while current_query < num_queries:
        current_query += 1
        q_offsets[current_query] = len(q_records)
        
    return q_offsets


@njit(inline='always')
def _tally_single_query(
        start: int, end: int,
        q_records: npt.NDArray,
        t_records: npt.NDArray,
        tally: npt.NDArray[np.uint32], anchors: npt.NDArray[np.int32]
):
    for i in range(start, end):
        q_rec = q_records[i]
        h = q_rec['hash']
        q_p = q_rec['pos1']

        # Manual binary search (searchsorted_left)
        low, high = 0, len(t_records)
        while low < high:
            mid = (low + high) // 2
            if t_records[mid]['hash'] < h:
                low = mid + 1
            else:
                high = mid
                
        curr = low

        # Walk forward to handle all collisions (handles out-of-bounds seamlessly)
        while curr < len(t_records) and t_records[curr]['hash'] == h:
            t_rec = t_records[curr]
            t_id = t_rec['seq_idx']
            tally[t_id] += 1
            if tally[t_id] == 1:
                    anchors[t_id] = np.int32(q_p) - np.int32(t_rec['pos1'])
            curr += 1


@njit(parallel=True, cache=True, nogil=True)
def _intersect_top_hit_kernel(
        q_records, q_offsets, num_queries,
        t_records, num_targets
):
    best_t = np.zeros(num_queries, dtype=np.uint32)
    max_s = np.zeros(num_queries, dtype=np.uint32)
    offsets = np.zeros(num_queries, dtype=np.int32)

    for q_idx in prange(num_queries): # type: ignore
        start, end = q_offsets[q_idx], q_offsets[q_idx + 1]
        if start == end: continue

        # Thread-local allocations (Fits cleanly in L1 Cache)
        tally = np.zeros(num_targets, dtype=np.uint32)
        anchors = np.zeros(num_targets, dtype=np.int32)

        # The inline directive injects the binary search code directly here
        _tally_single_query(start, end, q_records, t_records, tally, anchors)

        # Argmax Search
        best_score, best_target = 0, 0
        for t in range(num_targets):
            if tally[t] > best_score:
                best_score = tally[t]
                best_target = t

        best_t[q_idx] = best_target
        max_s[q_idx] = best_score
        offsets[q_idx] = anchors[best_target]

    # Return dense arrays, returning q_idx explicitly for easy zipping
    q_idx_arr = np.arange(num_queries, dtype=np.uint32)
    return q_idx_arr, best_t, max_s, offsets
